# Copyright (c) 2020 Cisco and/or its affiliates.
#
# This software is licensed to you under the terms of the Cisco Sample
# Code License, Version 1.1 (the "License"). You may obtain a copy of the
# License at
#
#                https://developer.cisco.com/docs/licenses
#
# All use of the material herein must be in accordance with the terms of
# the License. All rights not expressly granted by the License are
# reserved. Unless required by applicable law or agreed to separately in
# writing, software distributed under the License is distributed on an "AS
# IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
# or implied.

devices:
  device_name: __device_name__
  hw_platform: ansible_net_platform
  os_type: ansible_network_os
  os_version: ansible_net_version
enabled_features:
  device_name: __device_name__
  feature_name: "ansible_net_features_enabled"
vlans:
  device_name: __device_name__
  vlan: "ansible_net__vlan_list"
mac_address_table:
  device_name: __device_name__
  __net_mac_address_table:
    vlan: "vlan"
    interface: "port"
    mac_address: "mac_address"
    type: "type"
arp_vrf_BRKDCN_2937:
  device_name: __device_name__
  __net_arp_vrf_BRKDCN_2937:
    ip_address: "address"
    interface: "interface"
    mac_address: "mac_address"
hsrp_groups:
  device_name: __device_name__
  __net_hsrp:
    group_id: "group_id"
    interface: "interface"
    priority: "priority"
    state: "state"
    group_address: "group_address"
    active_address: "active_address"
    standby_address: "standby_address"
all_interfaces:
  device_name: __device_name__
  __ansible_facts:
    __network_resources:
      __interfaces:
        name: "name"
        enabled: "enabled"
        description: "description"
l2_interfaces:
  device_name: __device_name__
  __ansible_facts:
    __network_resources:
      __l2_interfaces:
        name: "name"
        __trunk:
          allowed_vlans: "allowed_vlans"
l3_interfaces:
  device_name: __device_name__
  __ansible_facts:
    __network_resources:
      __l3_interfaces:
        name: "name"
        __ipv4:
          ipv4_address: "address"
