# Copyright (c) 2020 Cisco and/or its affiliates.
#
# This software is licensed to you under the terms of the Cisco Sample
# Code License, Version 1.1 (the "License"). You may obtain a copy of the
# License at
#
#                https://developer.cisco.com/docs/licenses
#
# All use of the material herein must be in accordance with the terms of
# the License. All rights not expressly granted by the License are
# reserved. Unless required by applicable law or agreed to separately in
# writing, software distributed under the License is distributed on an "AS
# IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
# or implied.

---
- name: Prepare Layer-3 Migration (ACI)
  hosts: aci
  gather_facts: False
  tasks:
    - name: Associate BD (wordpress_bd) to L3out(s)
      aci_bd_to_l3out:
        host: '{{ inventory_hostname }}'
        username: '{{ apic_username }}'
        password: '{{ apic_password }}' 
        validate_certs: false
        tenant: BRKDCN-2937
        bd: wordpress_db
        l3out: "{{ item }}"
        state: present
      delegate_to: localhost
      loop:
        - "Campus_Uplink"
        - "Existing_Interconnect"
    - name: Create Contract (wordpress_db)
      aci_contract:
        host: '{{ inventory_hostname }}'
        username: '{{ apic_username }}'
        password: '{{ apic_password }}' 
        validate_certs: false
        tenant: BRKDCN-2937
        contract: wordpress_db
        scope: context
        state: present
      delegate_to: localhost
    - name: Create Contract Subject (wordpress_db/db)
      aci_contract_subject:
        host: '{{ inventory_hostname }}'
        username: '{{ apic_username }}'
        password: '{{ apic_password }}' 
        validate_certs: false
        tenant: BRKDCN-2937
        contract: wordpress_db
        subject: db
        reverse_filter: yes
        state: present
      delegate_to: localhost
    - name: Create Contract Filter (tcp_3306)
      aci_filter:
        host: '{{ inventory_hostname }}'
        username: '{{ apic_username }}'
        password: '{{ apic_password }}' 
        validate_certs: false
        tenant: BRKDCN-2937
        filter: tcp_3306
        state: present
      delegate_to: localhost
    - name: Create Contract Filter Entry (tcp_3306)
      aci_filter_entry:
        host: '{{ inventory_hostname }}'
        username: '{{ apic_username }}'
        password: '{{ apic_password }}' 
        validate_certs: false
        tenant: BRKDCN-2937
        filter: tcp_3306
        entry: tcp_3306
        ether_type: ip
        ip_protocol: tcp
        dst_port: "3306"
        state: present
      delegate_to: localhost
    - name: Associate Contract Filter (tcp_3306) to Subject (wordpress_db/db)
      aci_contract_subject_to_filter:
        host: '{{ inventory_hostname }}'
        username: '{{ apic_username }}'
        password: '{{ apic_password }}' 
        validate_certs: false
        tenant: BRKDCN-2937
        contract: wordpress_db
        subject: db
        filter: tcp_3306
        state: present
      delegate_to: localhost
    - name: Provide Contract (wordpress_db) by EPG
      aci_epg_to_contract:  
        host: '{{ inventory_hostname }}'
        username: '{{ apic_username }}'
        password: '{{ apic_password }}' 
        validate_certs: false
        tenant: BRKDCN-2937
        ap: wordpress
        epg: db
        contract: wordpress_db
        contract_type: provider
        state: present
      delegate_to: localhost
    - name: Consume Contract (wordpress_db) by External EPG
      aci_rest:  
        host: '{{ inventory_hostname }}'
        username: '{{ apic_username }}'
        password: '{{ apic_password }}' 
        validate_certs: false
        path: /api/mo/uni/tn-BRKDCN-2937/out-Existing_Interconnect/instP-existing_dc.json
        method: post
        content:
          fvRsCons:
            attributes:
              tnVzBrCPName: "wordpress_db"
              status: "created,modified"
      delegate_to: localhost

- name: Perform Layer-3 Migration (NXOS)
  hosts: nxos
  gather_facts: False
  tasks:
    - name: Shutdown VLAN in existing Network
      nxos_config:
        lines:
          - shutdown
        parents: interface Vlan130
        save_when: modified

- name: Perform Layer-3 Migration (ACI)
  hosts: aci
  gather_facts: False
  tasks:
    - name: Change BD (wordpress_db) to L3 Mode
      aci_bd:
        host: '{{ inventory_hostname }}'
        username: '{{ apic_username }}'
        password: '{{ apic_password }}' 
        validate_certs: false
        tenant: BRKDCN-2937
        vrf: main
        bd: wordpress_db
        mac_address: "00:00:0C:07:AC:82"
        enable_routing: yes
        arp_flooding: no
        l2_unknown_unicast: proxy
        l3_unknown_multicast: flood
        multi_dest: bd-flood
        state: present
      delegate_to: localhost
    - name: Add subnet to BD (wordpress_db)
      aci_bd_subnet:
        host: '{{ inventory_hostname }}'
        username: '{{ apic_username }}'
        password: '{{ apic_password }}' 
        validate_certs: false
        tenant: BRKDCN-2937
        bd: wordpress_db
        subnet_name: wordpress_db
        gateway: 100.64.130.1
        mask: 24
        scope: public
        state: present
      delegate_to: localhost
